# Molecule managed

---
all:
  hosts:
    master: &id001
      ansible_host: 127.0.0.1
      ansible_port: '2222'
      ansible_private_key_file: /Users/alain/Documents/dev/remote-keygen/molecule/default/.molecule/.vagrant/machines/master/virtualbox/private_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: vagrant
      connection: ssh
ungrouped:
  hosts:
    master: *id001
  vars: {}
